version: '3.9'
services:
  deprecatedbot:
    image: ghcr.io/yanorei32/deprecated-bot:0.1.2@sha256:41b5e1901940ad1ada56f9228a10b9246077a4b11146a3c28532e6e59a4c8843

    hostname: deprecatedbot
    container_name: deprecatedbot__deprecatedbot

    restart: unless-stopped

    environment:
      TARGET: ${TARGET}
      TRIGGER: ${TRIGGER}
      TOKEN: ${TOKEN}

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: deprecatedbot__default
